" ----------
" Vim Config
" ----------
"
" TL;DR
" Run install.sh to symlink this file to your home directory (e.g. $HOME/.vimrc)
"
" How this works:
"
" This file is minimal.  Most of the vim settings and initialization is in
" several files in .vim/init.  This makes it easier to find things and to
" merge between branches and repos.
"
" Please do not add configuration to this file, unless it *really* needs to
" come first or last, like vundle. Instead, add it to one of the files in
" .vim/init, or create a new one.

set nocompatible                " Don't maintain compatibility with vi

" Vim plugins
call plug#begin()

Plug 'vim-syntastic/syntastic'
Plug 'joshdick/onedark.vim'
Plug 'tpope/vim-fugitive'
" Plug 'tpope/vim-surround'
Plug 'scrooloose/nerdtree'
" Plug 'scrooloose/nerdcommenter'
" Plug 'mileszs/ack.vim'
" Plug 'tpope/vim-repeat'
" Plug 'plasticboy/vim-markdown'
" Plug 'tpope/vim-unimpaired'
" Plug 'godlygeek/tabular'
" Plug 'ervandew/supertab'
Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'tomtom/tlib_vim'
Plug 'garbas/vim-snipmate'
" Plug 'kien/ctrlp.vim'
Plug 'airblade/vim-gitgutter'
Plug 'vim-airline/vim-airline'
Plug 'pangloss/vim-javascript'

call plug#end()

" Source initialization files
runtime! init/**.vim
