llpppp;llnnnnnnnnnnnnnnnnnnnnnnnnnnnkj…………export GOPATH=$(go env GOPATH)

source ~/.aliases
source ~/.bash_ps1

# Directories to be prepended to $PATH
declare -a dirs_to_prepend
dirs_to_prepend=(
  "/bin"
  "/sbin"
  "/usr/sbin"
  "/usr/bin"
  "/usr/local/bin"
  "/usr/local/sbin"
  "/usr/local/git/bin"
  "/usr/local/"
  "/usr/local/mysql/bin"
  "/sw/bin/“:
  "$HOME/dotfiles/bin"
  "$HOME/bin"
  "$HOME/Library/Python/2.7/bin"
  "$HOME/go/bin"
  "/usr/local/opt/icu4c/bin"
  "/usr/local/opt/icu4c/sbin"
)

# Loop and assign path above
for dir in ${dirs_to_prepend[@]}
do
  if [ -d ${dir} ]; then
    # If these directories exist, then prepend them to existing PATH
    PATH="${dir}:$PATH"
  fi
done

unset dirs_to_prepend

export PATH

# ssh
export SSH_KEY_PATH="~/.ssh/id_rsa"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
